config/routes.rb
Rails.application.routes.draw do
  resources :tweets, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end
  
  root 'top#index'
  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    validates :content, presence: true
    validates_length_of :content, maximum: 255
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :update, :destroy]
  
  def index
    @tweets = Tweet.all
    # 値が初期化されない戻るボタン。
    # parametersを元にnewアクションを分岐させている。
    if params[:back]
      @tweet = Tweet.new(tweets_params)
    else
      @tweet = Tweet.new
    end
  end
  
  def new
    # 値が初期化されない戻るボタン。
    # parametersを元にnewアクションを分岐させている。
    if params[:back]
      @tweet = Tweet.new(tweets_params)
    else
      @tweet = Tweet.new
    end
  end
  
  def create
   @tweet = Tweet.new(tweets_params)
    # if文の作成
    if @tweet.save
      # 一覧画面へ遷移して"ツイートを投稿しました"とフィードバックメッセージを表示する
      redirect_to tweets_path, notice: "ツイートを投稿しました"
    else
      # 入力フォームを再描画する
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    @tweet.update(tweets_params)
    if @tweet.save
      redirect_to tweets_path, notice:"ツイートを編集しました！"
    else
      render 'new'
    end
  end
  
  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: "ツイートを削除しました"
  end
  
  def confirm
    @tweet = Tweet.new(tweets_params)
    render :new if @tweet.invalid?
  end
  
  private
    def tweets_params
      params.require(:tweet).permit(:content)
    end
    
    # edit, update, destroyで共通コード
    # idをキーとして値を取得するメソッド
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_tweets_path
    elsif action_name == 'edit'
      tweet_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= yield %>

  <footer>
    <p>Twitterアプリ練習</p>
  </footer>

</body>
</html>

app/views/top/index.html.erb
<header class="top">
  <section class="header-icon">
    <%= link_to image_tag('twitter_icon.png'), root_path %>
  </section>
  <section class="main-header">
　  <h1>いまどうしてる？</h1>
    <ul class="top">
      <li class="top"><%= link_to "アカウント作成", tweets_path, class: 'btn btn-primary btn-lg' %></li>
      <li class="top"><%= link_to "ログイン", tweets_path, class: 'btn btn-primary btn-lg' %></li>
    </ul>
  </section>
  <div class="btn-group btn-group-justified">
    <a class="btn btn-default">🔍</a>
    <a class="btn btn-default">トップ</a>
    <a class="btn btn-default">エンタメ</a>
    <a class="btn btn-default">音楽</a>
    <a class="btn btn-default">スポーツ</a>
    <a class="btn btn-default">ライフスタイル</a>
    <a class="btn btn-default">アニメ・漫画</a>
    <a class="btn btn-default">その他</a>
   </div>
</header>

<section class="about">
  <h2>Twittr風アプリケーション</h2>
    <p>
      このサイトはruby on railsの練習に作成されました。<br>
      「ログイン」または「アカウント作成」からご利用ください。
    </p>
</section>

app/views/tweets/_form.html.erb
<div class="tweet-form">
  <%= form_for(@tweet, url: choose_new_or_edit) do |f| %>
    <% if @tweet.errors.any? %>
      <div id="error_explanation">
        <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>

        <ul>
          <% @tweet.errors.full_messages.each do |msg| %>
          <li class="tweet-error"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.text_field :content, class: 'form-control', placeholder:"いまどうしてる？" %>
     <span class="count "><!--ここに表示入力可能の残り文字数を表示 --></span>
      <br><div class="tweet-submit">
        <%= image_submit_tag("tweet_btn.png") %>
      </div>
    <% end %>
</div>

<%= link_to "×", tweets_path %>

app/views/tweets/_header.html.erb
<header class="tweet">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag('twitter_icon.png'), root_path, class: "navbar-brand" %></li>
        <%= link_to "ホーム", root_path, class: "navbar-brand" %>
        <%= link_to "通知", tweets_path, class: "navbar-brand" %>
        <%= link_to "メッセージ", tweets_path, class: "navbar-brand" %>
        <%= link_to "ツイート一覧", tweets_path, class: "navbar-brand" %>
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to image_tag('tweet.png'), new_tweet_path %></li>
        <li><%= link_to image_tag('profile01.jpg'), tweets_path %> </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">プロフィール編集</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">設定</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">ログアウト</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/tweets/confirm.html.erb
<%= render 'header' %>

<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、投稿する</h3>

    <%= form_for(@tweet) do |f| %>
      <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定できるようにしている。 -->
      <%= f.hidden_field :content %>
      <!-- @tweet.contentとすることで、表示用の値を画面に出力している。 -->
      <p>ツイート:<%= @tweet.content %></p>
      <%= f.submit "投稿する", class: 'btn btn-primary btn-block' %>
    <% end %>

    <%= form_for(@tweet, url: new_tweet_path, method: 'get') do |f| %>
      <%= f.hidden_field :content %>
      <%= f.submit "戻る", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/tweets/edit.html.erb
<%= render 'header' %>

<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ツイートを編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/tweets/index.html.erb
<%= render 'header' %>

<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p>
      下のフォーム、またはメニューのツイートマークから<br>
    　ツイート投稿画面に移動してツイートを投稿できます。
    </p>

    <p><%= notice %></p>
    
    <div class="tweet-form">
      <%= form_for(@tweet, url: choose_new_or_edit) do |f| %>
        <% if @tweet.errors.any? %>
        <div id="error_explanation">
          <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>

          <ul>
          <% @tweet.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.text_field :content, class: 'form-control', placeholder:"いまどうしてる？" %>
        <div class="top-submit">
          <span class="count "><!--ここに表示入力可能の残り文字数を表示 --></span>
          <%= image_submit_tag("tweet_btn.png") %>
        </div>
      <% end %>
    </div>
    
    <% @tweets.each do |tweet| %>
      <div class="row">
        <p><img src="<%= asset_path "profile01.jpg" %>", title="profile画像",  width="30px" height="30px"><%= tweet.content %></p>
        <%= link_to "ツイートを編集する", edit_tweet_path(tweet.id), class: 'btn btn-default btn-sm btn-success' %>
        <%= link_to 'ツイートを削除する', tweet_path(tweet.id), method: :delete, data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-default btn-sm btn btn-danger' %>
      </div>
    <% end %>
  </div>
</div>

<div id="page-top-btn" class="page-top-btn">
  <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>

app/views/tweets/new.html.erb
<%= render 'header' %>

<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ツイートを投稿する</h2>
    <%= render 'form' %>
  </div>
</div>